set define off
set sqlblanklines on
spool AR-RELEASE-5_4_1-Upgrade-ORACLE-Install.log


-- RES-752
alter table SPECIAL_REVIEW add UNIT_ADMINISTRATOR_TYPE_CODE VARCHAR2(3);

CREATE INDEX "IX_SPECREV_UATYPECODE" ON "SPECIAL_REVIEW" ("UNIT_ADMINISTRATOR_TYPE_CODE");

Insert into UNIT_ADMINISTRATOR_TYPE (UNIT_ADMINISTRATOR_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,DEFAULT_GROUP_FLAG,MULTIPLES_FLAG,OBJ_ID) 
values ('700','Export Control Coordinator',SYSDATE,'admin',1,'C','Y',SYS_GUID());

Insert into UNIT_ADMINISTRATOR_TYPE (UNIT_ADMINISTRATOR_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,DEFAULT_GROUP_FLAG,MULTIPLES_FLAG,OBJ_ID) 
values ('701','Biosafety Coordinator',SYSDATE,'admin',1,'C','Y',SYS_GUID());

update SPECIAL_REVIEW set UNIT_ADMINISTRATOR_TYPE_CODE='700' where SPECIAL_REVIEW_CODE='8';
update SPECIAL_REVIEW set UNIT_ADMINISTRATOR_TYPE_CODE='701' where SPECIAL_REVIEW_CODE='14';




commit;
exit
