set define off
set sqlblanklines on
spool AR-RELEASE-5_4_0-Upgrade-ORACLE-Install.log

-- change TBN.TBN_ID from VARCHAR to NUMBER
alter table TBN add TBN_ID_2 NUMBER;
update TBN set TBN_ID_2 = TO_NUMBER(TBN_ID);
ALTER TABLE    TBN drop constraint    TBNP1;
update TBN set TBN_ID = null;
alter table TBN modify (TBN_ID NUMBER);
update TBN set TBN_ID = TBN_ID_2;
alter table TBN ADD CONSTRAINT PK_TBNID PRIMARY KEY (TBN_ID);
alter table TBN drop column TBN_ID_2;

-- change BUDGET_PERSONS.TBN_ID from VARCHAR to NUMBER
alter table BUDGET_PERSONS add TBN_ID_2 NUMBER;
update BUDGET_PERSONS set TBN_ID_2 = TO_NUMBER(TBN_ID);
update BUDGET_PERSONS set TBN_ID = null;
alter table BUDGET_PERSONS modify (TBN_ID NUMBER);
update BUDGET_PERSONS set TBN_ID = TBN_ID_2;
alter table BUDGET_PERSONS drop column TBN_ID_2;


-- RES-583
CREATE INDEX "IX_AWARD_SPONSORCODE" ON "AWARD" ("SPONSOR_CODE");
CREATE INDEX "IX_AWARD_STATUSCODE" ON "AWARD" ("STATUS_CODE") ;
CREATE INDEX "IX_AWARD_UNITNUM" ON "AWARD" ("LEAD_UNIT_NUMBER");
CREATE INDEX "IX_AWARD_TRANSTYPECODE" ON "AWARD" ("TRANSACTION_TYPE_CODE");
CREATE INDEX "IX_AWARD_ACTTYPECODE" ON "AWARD" ("ACTIVITY_TYPE_CODE");
CREATE INDEX "IX_AWARD_AWARDTYPECODE" ON "AWARD" ("AWARD_TYPE_CODE");
CREATE INDEX "IX_AWARD_PRIMESPONSOR" ON "AWARD" ("PRIME_SPONSOR_CODE");
CREATE INDEX "IX_AWARD_METHPAYCODE" ON "AWARD" ("METHOD_OF_PAYMENT_CODE");
CREATE INDEX "IX_AWARD_PROCPRIORCODE" ON "AWARD" ("PROCUREMENT_PRIORITY_CODE");
CREATE INDEX "IX_AWARD_BASISPAYCODE" ON "AWARD" ("BASIS_OF_PAYMENT_CODE");
CREATE INDEX "IX_AWARD_TEMPLATECODE" ON "AWARD" ("TEMPLATE_CODE");
CREATE INDEX "IX_AWARD_NSFCODE" ON "AWARD" ("NSF_CODE");
CREATE INDEX "IX_AWARD_ACCOUNTCODE" ON "AWARD" ("ACCOUNT_TYPE_CODE");
CREATE INDEX "IX_AWARD_FINCHARTSCODE" ON "AWARD" ("FIN_CHART_OF_ACCOUNTS_CODE");

-- RES-584
CREATE INDEX "IX_AWARDCOM_TYPECODE" ON "AWARD_COMMENT" ("COMMENT_TYPE_CODE");

-- RES-585
CREATE INDEX "IX_AWDREPTRMS_REPCLASSCODE" ON "AWARD_REPORT_TERMS" ("REPORT_CLASS_CODE");
CREATE INDEX "IX_AWDREPTRMS_REPCODE" ON "AWARD_REPORT_TERMS" ("REPORT_CODE");
CREATE INDEX "IX_AWDREPTRMS_FREQCODE" ON "AWARD_REPORT_TERMS" ("FREQUENCY_CODE");
CREATE INDEX "IX_AWDREPTRMS_FREQBASECODE" ON "AWARD_REPORT_TERMS" ("FREQUENCY_BASE_CODE");
CREATE INDEX "IX_AWDREPTRMS_OSPDISTCODE" ON "AWARD_REPORT_TERMS" ("OSP_DISTRIBUTION_CODE");


-- RES-586
CREATE INDEX "IX_AWDREPTRK_01" ON "AWARD_REPORT_TRACKING" ("AWARD_REPORT_TERM_ID");
CREATE INDEX "IX_AWDREPTRK_02" ON "AWARD_REPORT_TRACKING" ("AWARD_NUMBER");
CREATE INDEX "IX_AWDREPTRK_03" ON "AWARD_REPORT_TRACKING" ("PI_PERSON_ID");
CREATE INDEX "IX_AWDREPTRK_04" ON "AWARD_REPORT_TRACKING" ("PI_ROLODEX_ID");
CREATE INDEX "IX_AWDREPTRK_05" ON "AWARD_REPORT_TRACKING" ("LEAD_UNIT_NUMBER");
CREATE INDEX "IX_AWDREPTRK_06" ON "AWARD_REPORT_TRACKING" ("REPORT_CLASS_CODE");
CREATE INDEX "IX_AWDREPTRK_07" ON "AWARD_REPORT_TRACKING" ("REPORT_CODE");
CREATE INDEX "IX_AWDREPTRK_08" ON "AWARD_REPORT_TRACKING" ("FREQUENCY_CODE");
CREATE INDEX "IX_AWDREPTRK_09" ON "AWARD_REPORT_TRACKING" ("FREQUENCY_BASE_CODE");
CREATE INDEX "IX_AWDREPTRK_10" ON "AWARD_REPORT_TRACKING" ("OSP_DISTRIBUTION_CODE");
CREATE INDEX "IX_AWDREPTRK_11" ON "AWARD_REPORT_TRACKING" ("STATUS_CODE");
CREATE INDEX "IX_AWDREPTRK_12" ON "AWARD_REPORT_TRACKING" ("SPONSOR_CODE");
CREATE INDEX "IX_AWDREPTRK_13" ON "AWARD_REPORT_TRACKING" ("SPONSOR_AWARD_NUMBER");

-- RES-587
CREATE INDEX "IX_AWDSPONCON_01" ON "AWARD_SPONSOR_CONTACTS" ("AWARD_ID");
CREATE INDEX "IX_AWDSPONCON_02" ON "AWARD_SPONSOR_CONTACTS" ("AWARD_NUMBER","SEQUENCE_NUMBER");
CREATE INDEX "IX_AWDSPONCON_03" ON "AWARD_SPONSOR_CONTACTS" ("ROLODEX_ID");
CREATE INDEX "IX_AWDSPONCON_04" ON "AWARD_SPONSOR_CONTACTS" ("CONTACT_ROLE_CODE");


-- RES-588
CREATE INDEX "IX_AWDUNITCONTACTS_01" ON "AWARD_UNIT_CONTACTS" ("AWARD_ID");
CREATE INDEX "IX_AWDUNITCONTACTS_02" ON "AWARD_UNIT_CONTACTS" ("AWARD_NUMBER","SEQUENCE_NUMBER");
CREATE INDEX "IX_AWDUNITCONTACTS_03" ON "AWARD_UNIT_CONTACTS" ("PERSON_ID");
CREATE INDEX "IX_AWDUNITCONTACTS_04" ON "AWARD_UNIT_CONTACTS" ("UNIT_ADMINISTRATOR_TYPE_CODE");
CREATE INDEX "IX_AWDUNITCONTACTS_05" ON "AWARD_UNIT_CONTACTS" ("UNIT_ADMINISTRATOR_UNIT_NUMBER");

-- RES-589
CREATE INDEX "IX_AWDSPONTERM_02" ON "AWARD_SPONSOR_TERM" ("AWARD_NUMBER","SEQUENCE_NUMBER");

-- RES-590
CREATE INDEX "IX_AWDAMTINFO_01" ON "AWARD_AMOUNT_INFO" ("TNM_DOCUMENT_NUMBER");

-- RES-591
CREATE INDEX "IX_AWDHIER_01" ON "AWARD_HIERARCHY" ("AWARD_NUMBER","ACTIVE");
CREATE INDEX "IX_AWDHIER_02" ON "AWARD_HIERARCHY" ("ROOT_AWARD_NUMBER","ACTIVE");

-- RES-592
CREATE INDEX "IX_AWDPERUNITS_AWDPERSID" ON "AWARD_PERSON_UNITS" ("AWARD_PERSON_ID");
CREATE INDEX "IX_AWDPERUNITS_UNITNUM" ON "AWARD_PERSON_UNITS" ("UNIT_NUMBER");


 -- RES-514
  CREATE TABLE "PROTOCOL_KEYWORD" 
   (	"PROTOCOL_KEYWORD_ID" NUMBER(12,0), 
	"PROTOCOL_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"VER_NBR" NUMBER(8,0) DEFAULT 1 NOT NULL ENABLE, 
	"KEYWORD_CODE" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL ENABLE, 
	"OBJ_ID" VARCHAR2(36 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PROTOCOL_KEYWORDP1" PRIMARY KEY ("PROTOCOL_KEYWORD_ID")
  USING INDEX COMPUTE STATISTICS  ENABLE, 
	 CONSTRAINT "FK_PROTOCOL_KEYWORD2" FOREIGN KEY ("KEYWORD_CODE")
	  REFERENCES "SCIENCE_KEYWORD" ("SCIENCE_KEYWORD_CODE") ENABLE, 
	 CONSTRAINT "FK_PROTOCOL_KEYWORD" FOREIGN KEY ("PROTOCOL_ID")
	  REFERENCES "PROTOCOL" ("PROTOCOL_ID") ENABLE
   );

  CREATE INDEX "IX_PROTOCOL_KEY_PROT_ID" ON "PROTOCOL_KEYWORD" ("PROTOCOL_ID") COMPUTE STATISTICS; 
  CREATE INDEX "IX_PROTOCOL_KEY_SCICODE" ON "PROTOCOL_KEYWORD" ("KEYWORD_CODE") COMPUTE STATISTICS; 


  CREATE SEQUENCE "SEQ_PROTOCOL_KEYWORD_ID"  MINVALUE 1 MAXVALUE 9999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;



-- RES-515

  CREATE TABLE "IACUC_PROTOCOL_KEYWORD" 
   (	"IACUC_PROTOCOL_KEYWORD_ID" NUMBER(12,0), 
	"IACUC_PROTOCOL_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"VER_NBR" NUMBER(8,0) DEFAULT 1 NOT NULL ENABLE, 
	"KEYWORD_CODE" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL ENABLE, 
	"OBJ_ID" VARCHAR2(36 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "IACUC_PROTOCOL_KEYWORDP1" PRIMARY KEY ("IACUC_PROTOCOL_KEYWORD_ID")
  USING INDEX COMPUTE STATISTICS  ENABLE, 
	 CONSTRAINT "FK_IACUC_PROTOCOL_KEYWORD2" FOREIGN KEY ("KEYWORD_CODE")
	  REFERENCES "SCIENCE_KEYWORD" ("SCIENCE_KEYWORD_CODE") ENABLE, 
	 CONSTRAINT "FK_IACUC_PROTOCOL_KEYWORD" FOREIGN KEY ("IACUC_PROTOCOL_ID")
	  REFERENCES "IACUC_PROTOCOL" ("PROTOCOL_ID") ENABLE
   );

  CREATE INDEX "IX_IACUC_PROTOCOL_KEY_PROT_ID" ON "IACUC_PROTOCOL_KEYWORD" ("IACUC_PROTOCOL_ID") COMPUTE STATISTICS; 
  CREATE INDEX "IX_IACUC_PROTOCOL_KEY_SCICODE" ON "IACUC_PROTOCOL_KEYWORD" ("KEYWORD_CODE") COMPUTE STATISTICS; 


  CREATE SEQUENCE "SEQ_IACUC_PROTOCOL_KEYWORD_ID"  MINVALUE 1 MAXVALUE 9999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;


 -- RES-548
update NARRATIVE_TYPE set DESCRIPTION='Project Summary' where DESCRIPTION='ProjectSummary';
update NARRATIVE_TYPE set DESCRIPTION='Budget Justification' where DESCRIPTION='BudgetJustification';
update NARRATIVE_TYPE set DESCRIPTION='Subaward Budget' where DESCRIPTION='SubawardBudget';
update NARRATIVE_TYPE set DESCRIPTION='Table of Contents' where DESCRIPTION='TableofContents';
update NARRATIVE_TYPE set DESCRIPTION='Supplementary Documentation' where DESCRIPTION='SupplementaryDocumentation';
update NARRATIVE_TYPE set DESCRIPTION='Additional Congressional Districts' where DESCRIPTION='AdditionalCongressionalDistricts';
update NARRATIVE_TYPE set DESCRIPTION='Personal Data' where DESCRIPTION='PersonalData';
update NARRATIVE_TYPE set DESCRIPTION='Additional Equipment' where DESCRIPTION='Additionalequipment';
update NARRATIVE_TYPE set DESCRIPTION='Additional Key Persons' where DESCRIPTION='Additionalkeypersons';
update NARRATIVE_TYPE set DESCRIPTION='Current Pending' where DESCRIPTION='CurrentPending';

-- RES-647
alter table COI_DISCL_PROJECTS MODIFY COI_PROJECT_TITLE VARCHAR2(2000);

-- RES-648
alter table AWARD_TEMPLATE disable constraint FK_AWARD_TEMPLATE_SPONSOR;
alter table NEGOTIATION_UNASSOC_DETAIL disable constraint NEGOTIATION_UNASSOC_DETAIL_FK3;
alter table NEGOTIATION_UNASSOC_DETAIL disable constraint NEGOTIATION_UNASSOC_DETAIL_FK4;
alter table PROPOSAL disable constraint FK_PROPOSAL_SPONSOR_CODE;
alter table SPONSOR_HIERARCHY disable constraint FK_SPONSOR_HIERARCHY_KRA;
alter table SPONSOR_FORMS disable constraint FK_SPONSOR_FORMS;
alter table SPONSOR_FORMS disable constraint SPONSOR_FORMSU1;
alter table AWARD_TRANSFERRING_SPONSOR disable constraint FK2_AWARD_TRANSFERRING_SPONSOR;

alter table AWARD_REPORT_TRACKING MODIFY SPONSOR_CODE VARCHAR2(12);
alter table SPONSOR_HIERARCHY_MT MODIFY SPONSOR_CODE VARCHAR2(12);
alter table PERSON_FIN_INT_DISCLOSURE MODIFY SPONSOR_CODE VARCHAR2(12);
alter table ROLODEX MODIFY SPONSOR_CODE VARCHAR2(12);
alter table PROPOSAL_LOG MODIFY SPONSOR_CODE VARCHAR2(12);
alter table EPS_PROPOSAL MODIFY SPONSOR_CODE VARCHAR2(12);
alter table EPS_PROPOSAL MODIFY PRIME_SPONSOR_CODE VARCHAR2(12);
alter table AWARD MODIFY SPONSOR_CODE VARCHAR2(12);
alter table AWARD MODIFY PRIME_SPONSOR_CODE VARCHAR2(12);

alter table NEGOTIATION_UNASSOC_DETAIL drop constraint "NEGOTIATION_UNASSOC_DETAIL_FK3";
alter table NEGOTIATION_UNASSOC_DETAIL drop constraint "NEGOTIATION_UNASSOC_DETAIL_FK4";
alter table NEGOTIATION_UNASSOC_DETAIL MODIFY SPONSOR_CODE VARCHAR2(12);
alter table NEGOTIATION_UNASSOC_DETAIL MODIFY PRIME_SPONSOR_CODE VARCHAR2(12);

alter table AWARD_TRANSFERRING_SPONSOR drop constraint "FK2_AWARD_TRANSFERRING_SPONSOR";
alter table AWARD_TRANSFERRING_SPONSOR MODIFY SPONSOR_CODE VARCHAR2(12);

alter table AWARD_TEMPLATE drop CONSTRAINT "FK_AWARD_TEMPLATE_SPONSOR";
alter table AWARD_TEMPLATE MODIFY PRIME_SPONSOR_CODE VARCHAR2(12);

alter table PROPOSAL drop CONSTRAINT "FK_PROPOSAL_SPONSOR_CODE";
alter table PROPOSAL MODIFY SPONSOR_CODE VARCHAR2(12);
alter table PROPOSAL MODIFY PRIME_SPONSOR_CODE VARCHAR2(12);

alter table SPONSOR_HIERARCHY drop CONSTRAINT "FK_SPONSOR_HIERARCHY_KRA";
alter table SPONSOR_HIERARCHY MODIFY SPONSOR_CODE VARCHAR2(12);

alter table SPONSOR_FORMS drop CONSTRAINT "FK_SPONSOR_FORMS";
alter table SPONSOR_FORMS MODIFY SPONSOR_CODE VARCHAR2(12);

alter table SPONSOR MODIFY SPONSOR_CODE VARCHAR2(12);

alter table NEGOTIATION_UNASSOC_DETAIL add CONSTRAINT "NEGOTIATION_UNASSOC_DETAIL_FK3" FOREIGN KEY ("SPONSOR_CODE") REFERENCES "SPONSOR" ("SPONSOR_CODE") ENABLE;
alter table NEGOTIATION_UNASSOC_DETAIL add CONSTRAINT "NEGOTIATION_UNASSOC_DETAIL_FK4" FOREIGN KEY ("PRIME_SPONSOR_CODE") REFERENCES "SPONSOR" ("SPONSOR_CODE") ENABLE;
alter table AWARD_TRANSFERRING_SPONSOR add CONSTRAINT "FK2_AWARD_TRANSFERRING_SPONSOR" FOREIGN KEY ("SPONSOR_CODE") REFERENCES "SPONSOR" ("SPONSOR_CODE") ENABLE;
alter table AWARD_TEMPLATE add CONSTRAINT "FK_AWARD_TEMPLATE_SPONSOR" FOREIGN KEY ("PRIME_SPONSOR_CODE") REFERENCES "SPONSOR" ("SPONSOR_CODE") ENABLE;
alter table PROPOSAL add CONSTRAINT "FK_PROPOSAL_SPONSOR_CODE" FOREIGN KEY ("SPONSOR_CODE") REFERENCES "SPONSOR" ("SPONSOR_CODE") ENABLE;
alter table SPONSOR_HIERARCHY add CONSTRAINT "FK_SPONSOR_HIERARCHY_KRA" FOREIGN KEY ("SPONSOR_CODE") REFERENCES "SPONSOR" ("SPONSOR_CODE") ON DELETE CASCADE ENABLE;
alter table SPONSOR_FORMS add CONSTRAINT "FK_SPONSOR_FORMS" FOREIGN KEY ("SPONSOR_CODE") REFERENCES "SPONSOR" ("SPONSOR_CODE") ENABLE;

-- RES-671
alter table PERSON_CUSTOM_DATA add PERSON_ID_NEW VARCHAR2(40);
update PERSON_CUSTOM_DATA set PERSON_ID_NEW=PERSON_ID;
update BUDGET_PERSONS set PERSON_ID = null;
alter table PERSON_CUSTOM_DATA modify PERSON_ID VARCHAR2(40);
update PERSON_CUSTOM_DATA set PERSON_ID=PERSON_ID_NEW;
alter table PERSON_CUSTOM_DATA drop column PERSON_ID_NEW;


 -- RES-545
alter table AWARD add ACTIVITY_TYPE_CODE_2 NUMBER;
update AWARD set ACTIVITY_TYPE_CODE_2 = ACTIVITY_TYPE_CODE;
alter table AWARD drop column ACTIVITY_TYPE_CODE;
alter table AWARD add ACTIVITY_TYPE_CODE VARCHAR2(3);
update AWARD set ACTIVITY_TYPE_CODE = ACTIVITY_TYPE_CODE_2;
alter table AWARD drop column ACTIVITY_TYPE_CODE_2;
alter table AWARD modify ACTIVITY_TYPE_CODE VARCHAR2(3) NOT NULL;



 -- RES-709 : NSF CoverPage v1.6
Insert into NARRATIVE_TYPE (NARRATIVE_TYPE_CODE,DESCRIPTION,SYSTEM_GENERATED,ALLOW_MULTIPLE,NARRATIVE_TYPE_GROUP,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) 
  values ('400','NSF Mentoring Plan','N','N','P',sysdate,'admin',1,sys_guid());

insert into VALID_NARR_FORMS (VALID_NARR_FORMS_ID,FORM_NAME,NARRATIVE_TYPE_CODE,MANDATORY,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) 
	values (SEQ_VALID_NARR_FORMS_ID.nextval,'NSF_CoverPage_1_6-V1.6',400,'N',sysdate,'admin',sys_guid())
/
insert into VALID_NARR_FORMS (VALID_NARR_FORMS_ID,FORM_NAME,NARRATIVE_TYPE_CODE,MANDATORY,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) 
	values (SEQ_VALID_NARR_FORMS_ID.nextval,'NSF_CoverPage_1_6-V1.6',200,'N',sysdate,'admin',sys_guid())
/
insert into VALID_NARR_FORMS (VALID_NARR_FORMS_ID,FORM_NAME,NARRATIVE_TYPE_CODE,MANDATORY,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) 
	values (SEQ_VALID_NARR_FORMS_ID.nextval,'NSF_CoverPage_1_6-V1.6',13,'N',sysdate,'admin',sys_guid())
/
insert into VALID_NARR_FORMS (VALID_NARR_FORMS_ID,FORM_NAME,NARRATIVE_TYPE_CODE,MANDATORY,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) 
	values (SEQ_VALID_NARR_FORMS_ID.nextval,'NSF_CoverPage_1_6-V1.6',14,'N',sysdate,'admin',sys_guid())
/
insert into VALID_NARR_FORMS (VALID_NARR_FORMS_ID,FORM_NAME,NARRATIVE_TYPE_CODE,MANDATORY,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) 
	values (SEQ_VALID_NARR_FORMS_ID.nextval,'NSF_CoverPage_1_6-V1.6',87,'N',sysdate,'admin',sys_guid())
/

INSERT INTO ARG_VALUE_LOOKUP(ARG_VALUE_LOOKUP_ID,ARGUMENT_NAME,VALUE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) values(100000,'NSFCoverPageFundingMechanism','RAPID','RAPID',sysdate,'admin',1,SYS_GUID());
INSERT INTO ARG_VALUE_LOOKUP(ARG_VALUE_LOOKUP_ID,ARGUMENT_NAME,VALUE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) values(100001,'NSFCoverPageFundingMechanism','EAGER','EAGER',sysdate,'admin',1,SYS_GUID());
INSERT INTO ARG_VALUE_LOOKUP(ARG_VALUE_LOOKUP_ID,ARGUMENT_NAME,VALUE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) values(100002,'NSFCoverPageFundingMechanism','Research - Other than RAPID or EAGER','Research - Other than RAPID or EAGER',sysdate,'admin',1,SYS_GUID());
INSERT INTO ARG_VALUE_LOOKUP(ARG_VALUE_LOOKUP_ID,ARGUMENT_NAME,VALUE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) values(100003,'NSFCoverPageFundingMechanism','Ideas Lab','Ideas Lab',sysdate,'admin',1,SYS_GUID());
INSERT INTO ARG_VALUE_LOOKUP(ARG_VALUE_LOOKUP_ID,ARGUMENT_NAME,VALUE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) values(100004,'NSFCoverPageFundingMechanism','International Travel','International Travel',sysdate,'admin',1,SYS_GUID());
INSERT INTO ARG_VALUE_LOOKUP(ARG_VALUE_LOOKUP_ID,ARGUMENT_NAME,VALUE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) values(100005,'NSFCoverPageFundingMechanism','Conference','Conference',sysdate,'admin',1,SYS_GUID());
INSERT INTO ARG_VALUE_LOOKUP(ARG_VALUE_LOOKUP_ID,ARGUMENT_NAME,VALUE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) values(100006,'NSFCoverPageFundingMechanism','Equipment','Equipment',sysdate,'admin',1,SYS_GUID());
INSERT INTO ARG_VALUE_LOOKUP(ARG_VALUE_LOOKUP_ID,ARGUMENT_NAME,VALUE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) values(100007,'NSFCoverPageFundingMechanism','Fellowship','Fellowship',sysdate,'admin',1,SYS_GUID());
INSERT INTO ARG_VALUE_LOOKUP(ARG_VALUE_LOOKUP_ID,ARGUMENT_NAME,VALUE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) values(100008,'NSFCoverPageFundingMechanism','Facility/Center','Facility/Center',sysdate,'admin',1,SYS_GUID());


Insert into QUESTIONNAIRE (QUESTIONNAIRE_REF_ID,QUESTIONNAIRE_ID,SEQUENCE_NUMBER,NAME,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_FINAL,VER_NBR,OBJ_ID,FILE_NAME,DOCUMENT_NUMBER) 
   values (SEQ_QUESTIONNAIRE_REF_ID.nextval,SEQ_QUESTIONNAIRE_ID.nextval,1,'NSF Cover Page v1.6 S2S form supporting questions',
   'These questions support  NSF Cover Page v1.6 Grants.gov forms.',
   sysdate,'admin','Y',1,sys_guid(),null,null);

Insert into QUESTIONNAIRE_USAGE (QUESTIONNAIRE_USAGE_ID,MODULE_ITEM_CODE,MODULE_SUB_ITEM_CODE,QUESTIONNAIRE_REF_ID_FK,QUESTIONNAIRE_SEQUENCE_NUMBER,QUESTIONNAIRE_LABEL,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,IS_MANDATORY,RULE_ID)
  values (SEQ_QUESTIONNAIRE_REF_ID.nextval,3,2,
  (select MAX(QUESTIONNAIRE_REF_ID) from QUESTIONNAIRE where NAME='NSF Cover Page v1.6 S2S form supporting questions'),
  1,'NSF Cover Page v1.6 S2S form supporting questions', sysdate,'admin',1,sys_guid(),'N',null);

Insert into S2S_FORM_TO_QUESTIONNAIRE (S2S_FORM_TO_QUESTIONNAIRE_ID,OPP_NAME_SPACE,FORM_NAME,QUESTIONNAIRE_ID,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID,VER_NBR) 
  values (SEQ_QUESTIONNAIRE_REF_ID.nextval,'http://apply.grants.gov/forms/NSF_CoverPage_1_6-V1.6','NSF_CoverPage_1_6-V1.6',
     (select MAX(QUESTIONNAIRE_ID) from QUESTIONNAIRE where NAME='NSF Cover Page v1.6 S2S form supporting questions'),sysdate,'admin',sys_guid(),1);




Insert into QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) 
   values (SEQ_QUESTIONNAIRE_REF_ID.nextval,101000,1,'A','Please select a Funding Mechanism.',
   'A',2,6,'org.kuali.kra.bo.ArgValueLookup','NSFCoverPageFundingMechanism',null,1,null,sysdate,'admin',1,sys_guid(),null);
   
Insert into QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,
     CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) 
  values (SEQ_QUESTIONNAIRE_REF_ID.nextval,
  (select MAX(QUESTIONNAIRE_REF_ID) from QUESTIONNAIRE where NAME='NSF Cover Page v1.6 S2S form supporting questions'),
  (select MAX(QUESTION_REF_ID) from QUESTION where QUESTION_ID=101000),
  5,0,'N',null,null,sysdate,'admin',5,1,SYS_GUID(),null);


Insert into QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,
     CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) 
  values (SEQ_QUESTIONNAIRE_REF_ID.nextval,
  (select MAX(QUESTIONNAIRE_REF_ID) from QUESTIONNAIRE where NAME='NSF Cover Page v1.6 S2S form supporting questions'),
  (select MAX(QUESTION_REF_ID) from QUESTION where QUESTION_ID=52),
  1,0,'N',null,null,sysdate,'admin',1,1,SYS_GUID(),null);

Insert into QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,
     CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) 
  values (SEQ_QUESTIONNAIRE_REF_ID.nextval,
  (select MAX(QUESTIONNAIRE_REF_ID) from QUESTIONNAIRE where NAME='NSF Cover Page v1.6 S2S form supporting questions'),
  (select MAX(QUESTION_REF_ID) from QUESTION where QUESTION_ID=53),
  2,0,'N',null,null,sysdate,'admin',2,1,SYS_GUID(),null);

Insert into QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,
     CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) 
  values (SEQ_QUESTIONNAIRE_REF_ID.nextval,
  (select MAX(QUESTIONNAIRE_REF_ID) from QUESTIONNAIRE where NAME='NSF Cover Page v1.6 S2S form supporting questions'),
  (select MAX(QUESTION_REF_ID) from QUESTION where QUESTION_ID=56),
  3,0,'N',null,null,sysdate,'admin',3,1,SYS_GUID(),null);

Insert into QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,
     CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) 
  values (SEQ_QUESTIONNAIRE_REF_ID.nextval,
  (select MAX(QUESTIONNAIRE_REF_ID) from QUESTIONNAIRE where NAME='NSF Cover Page v1.6 S2S form supporting questions'),
  (select MAX(QUESTION_REF_ID) from QUESTION where QUESTION_ID=10088),
  4,0,'N',null,null,sysdate,'admin',4,1,SYS_GUID(),null);

Insert into QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,
     CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) 
  values (SEQ_QUESTIONNAIRE_REF_ID.nextval,
  (select MAX(QUESTIONNAIRE_REF_ID) from QUESTIONNAIRE where NAME='NSF Cover Page v1.6 S2S form supporting questions'),
  (select MAX(QUESTION_REF_ID) from QUESTION where QUESTION_ID=65),
  6,3,'Y','4','Y',sysdate,'admin',1,1,SYS_GUID(),null);






 --RES-696 : Forms-D work

Insert into NARRATIVE_TYPE (NARRATIVE_TYPE_CODE,DESCRIPTION,SYSTEM_GENERATED,ALLOW_MULTIPLE,NARRATIVE_TYPE_GROUP,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID) 
  values ('146','PHS_ResearchPlan_KeyBiologicalAndOrChemicalResources','N','N','P',sysdate,'admin',1,sys_guid());


insert into VALID_NARR_FORMS (VALID_NARR_FORMS_ID,FORM_NAME,NARRATIVE_TYPE_CODE,MANDATORY,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) 
	values (SEQ_VALID_NARR_FORMS_ID.nextval,'PHS398_ResearchPlan_3_0',146,'N',sysdate,'admin',sys_guid())
/
insert into VALID_NARR_FORMS (VALID_NARR_FORMS_ID,FORM_NAME,NARRATIVE_TYPE_CODE,MANDATORY,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) 
	values (SEQ_VALID_NARR_FORMS_ID.nextval,'PHS398_ResearchPlan_3_0',111,'Y',sysdate,'admin',sys_guid())
/
insert into VALID_NARR_FORMS (VALID_NARR_FORMS_ID,FORM_NAME,NARRATIVE_TYPE_CODE,MANDATORY,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) 
	values (SEQ_VALID_NARR_FORMS_ID.nextval,'PHS398_ResearchPlan_3_0',20,'N',sysdate,'admin',sys_guid())
/
insert into VALID_NARR_FORMS (VALID_NARR_FORMS_ID,FORM_NAME,NARRATIVE_TYPE_CODE,MANDATORY,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) 
	values (SEQ_VALID_NARR_FORMS_ID.nextval,'PHS398_ResearchPlan_3_0',21,'N',sysdate,'admin',sys_guid())
/
insert into VALID_NARR_FORMS (VALID_NARR_FORMS_ID,FORM_NAME,NARRATIVE_TYPE_CODE,MANDATORY,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) 
	values (SEQ_VALID_NARR_FORMS_ID.nextval,'PHS398_ResearchPlan_3_0',25,'N',sysdate,'admin',sys_guid())
/
insert into VALID_NARR_FORMS (VALID_NARR_FORMS_ID,FORM_NAME,NARRATIVE_TYPE_CODE,MANDATORY,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) 
	values (SEQ_VALID_NARR_FORMS_ID.nextval,'PHS398_ResearchPlan_3_0',26,'N',sysdate,'admin',sys_guid())
/
insert into VALID_NARR_FORMS (VALID_NARR_FORMS_ID,FORM_NAME,NARRATIVE_TYPE_CODE,MANDATORY,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) 
	values (SEQ_VALID_NARR_FORMS_ID.nextval,'PHS398_ResearchPlan_3_0',28,'N',sysdate,'admin',sys_guid())
/ 
insert into VALID_NARR_FORMS (VALID_NARR_FORMS_ID,FORM_NAME,NARRATIVE_TYPE_CODE,MANDATORY,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) 
	values (SEQ_VALID_NARR_FORMS_ID.nextval,'PHS398_ResearchPlan_3_0',29,'N',sysdate,'admin',sys_guid())
/    
insert into VALID_NARR_FORMS (VALID_NARR_FORMS_ID,FORM_NAME,NARRATIVE_TYPE_CODE,MANDATORY,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) 
	values (SEQ_VALID_NARR_FORMS_ID.nextval,'PHS398_ResearchPlan_3_0',30,'N',sysdate,'admin',sys_guid())
/  
insert into VALID_NARR_FORMS (VALID_NARR_FORMS_ID,FORM_NAME,NARRATIVE_TYPE_CODE,MANDATORY,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) 
	values (SEQ_VALID_NARR_FORMS_ID.nextval,'PHS398_ResearchPlan_3_0',31,'N',sysdate,'admin',sys_guid())
/  
insert into VALID_NARR_FORMS (VALID_NARR_FORMS_ID,FORM_NAME,NARRATIVE_TYPE_CODE,MANDATORY,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) 
	values (SEQ_VALID_NARR_FORMS_ID.nextval,'PHS398_ResearchPlan_3_0',32,'N',sysdate,'admin',sys_guid())
/  
insert into VALID_NARR_FORMS (VALID_NARR_FORMS_ID,FORM_NAME,NARRATIVE_TYPE_CODE,MANDATORY,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) 
	values (SEQ_VALID_NARR_FORMS_ID.nextval,'PHS398_ResearchPlan_3_0',33,'N',sysdate,'admin',sys_guid())
/  
insert into VALID_NARR_FORMS (VALID_NARR_FORMS_ID,FORM_NAME,NARRATIVE_TYPE_CODE,MANDATORY,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) 
	values (SEQ_VALID_NARR_FORMS_ID.nextval,'PHS398_ResearchPlan_3_0',34,'N',sysdate,'admin',sys_guid())
/  
insert into VALID_NARR_FORMS (VALID_NARR_FORMS_ID,FORM_NAME,NARRATIVE_TYPE_CODE,MANDATORY,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) 
	values (SEQ_VALID_NARR_FORMS_ID.nextval,'PHS398_ResearchPlan_3_0',44,'N',sysdate,'admin',sys_guid())
/
insert into VALID_NARR_FORMS (VALID_NARR_FORMS_ID,FORM_NAME,NARRATIVE_TYPE_CODE,MANDATORY,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) 
	values (SEQ_VALID_NARR_FORMS_ID.nextval,'PHS398_ResearchPlan_3_0',45,'N',sysdate,'admin',sys_guid())
/
insert into VALID_NARR_FORMS (VALID_NARR_FORMS_ID,FORM_NAME,NARRATIVE_TYPE_CODE,MANDATORY,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) 
	values (SEQ_VALID_NARR_FORMS_ID.nextval,'PHS398_ResearchPlan_3_0',46,'N',sysdate,'admin',sys_guid())
/  

-- RES-696 : Forms-D work : phs-assignment-request-form
Insert into QUESTIONNAIRE (QUESTIONNAIRE_REF_ID,QUESTIONNAIRE_ID,SEQUENCE_NUMBER,NAME,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_FINAL,VER_NBR,OBJ_ID,FILE_NAME,DOCUMENT_NUMBER) 
   values (SEQ_QUESTIONNAIRE_REF_ID.nextval,SEQ_QUESTIONNAIRE_ID.nextval,1,
            'PHS Assignment Request Form V1.0','The responses are used to populate the PHS Assignment Request Form version 1.0 for submission via Grants.gov.',
            sysdate,'admin','Y',1,SYS_GUID(),null,null);
            
            
Insert into S2S_FORM_TO_QUESTIONNAIRE (S2S_FORM_TO_QUESTIONNAIRE_ID,OPP_NAME_SPACE,FORM_NAME,QUESTIONNAIRE_ID,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID,VER_NBR) 
  values (SEQ_QUESTIONNAIRE_REF_ID.nextval,'http://apply.grants.gov/forms/PHS_AssignmentRequestForm-V1.0','PHS_AssignmentRequestForm',
     (select MAX(QUESTIONNAIRE_ID) from QUESTIONNAIRE where NAME='PHS Assignment Request Form V1.0'),sysdate,'admin',sys_guid(),1);


Insert into QUESTIONNAIRE_USAGE (QUESTIONNAIRE_USAGE_ID,MODULE_ITEM_CODE,MODULE_SUB_ITEM_CODE,QUESTIONNAIRE_REF_ID_FK,QUESTIONNAIRE_SEQUENCE_NUMBER,QUESTIONNAIRE_LABEL,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,IS_MANDATORY,RULE_ID)
   values (SEQ_QUESTIONNAIRE_REF_ID.nextval,3,2, (select MAX(QUESTIONNAIRE_REF_ID) from QUESTIONNAIRE where NAME='PHS Assignment Request Form V1.0'), 1,'PHS Assignment Request Form V1.0',sysdate,'admin',1,sys_guid(),'Y',null);

-- 1. Awarding Component Assignment?
Insert into QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) 
   values (SEQ_QUESTIONNAIRE_REF_ID.nextval,100025,1,'A','If you have a preference for an Awarding Component (e.g., NIH Institute/Center) assignment, please use the link https://grants.nih.gov/grants/phs_assignment_information.htm#AwardingComponents to identify the most appropriate assignment then enter the short abbreviation (e.g., NCI for National Cancer Institute) in Assign to/Do Not Assign To Awarding Component sections below. Do you have a preference for an Awarding Component assignment?',
   'A',2,1,null,null,null,1,1,sysdate,'admin',1,sys_guid(),null);
   
Insert into QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,
     CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) 
  values (SEQ_QUESTIONNAIRE_REF_ID.nextval,
  (select MAX(QUESTIONNAIRE_REF_ID) from QUESTIONNAIRE where NAME='PHS Assignment Request Form V1.0'),
  (select MAX(QUESTION_REF_ID) from QUESTION where QUESTION_ID=100025),
  1,0,'N',null,null,sysdate,'admin',1,1,SYS_GUID(),null);

-- 1. Awarding Component Assignment?
Insert into QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) 
   values (SEQ_QUESTIONNAIRE_REF_ID.nextval,100025,1,'A','If you have a preference for an Awarding Component (e.g., NIH Institute/Center) assignment, please use the link https://grants.nih.gov/grants/phs_assignment_information.htm#AwardingComponents to identify the most appropriate assignment then enter the short abbreviation (e.g., NCI for National Cancer Institute) in Assign to/Do Not Assign To Awarding Component sections below. Do you have a preference for an Awarding Component assignment?',
   'A',2,1,null,null,null,1,1,sysdate,'admin',1,sys_guid(),null);
   
Insert into QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,
     CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) 
  values (SEQ_QUESTIONNAIRE_REF_ID.nextval,
  (select MAX(QUESTIONNAIRE_REF_ID) from QUESTIONNAIRE where NAME='PHS Assignment Request Form V1.0'),
  (select MAX(QUESTION_REF_ID) from QUESTION where QUESTION_ID=100025),
  1,0,'N',null,null,sysdate,'admin',1,1,SYS_GUID(),null);

-- 1a. Assign to Awarding Component?
Insert into QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) 
   values (SEQ_QUESTIONNAIRE_REF_ID.nextval,100026,1,'A','Do you need to assign to Awarding Component?',
   'A',2,1,null,null,null,1,1,sysdate,'admin',1,sys_guid(),null);
   
Insert into QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,
     CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) 
  values (SEQ_QUESTIONNAIRE_REF_ID.nextval,
  (select MAX(QUESTIONNAIRE_REF_ID) from QUESTIONNAIRE where NAME='PHS Assignment Request Form V1.0'),
  (select MAX(QUESTION_REF_ID) from QUESTION where QUESTION_ID=100026),
  2,1,'Y','4','Y',sysdate,'admin',2,1,SYS_GUID(),null);

-- 1ai. Assign to Awarding Component Fields?
Insert into QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) 
   values (SEQ_QUESTIONNAIRE_REF_ID.nextval,100027,1,'A','Assign to Awarding Component.',
   'A',4,5,null,null,null,3,7,sysdate,'admin',1,sys_guid(),null);
   
Insert into QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,
     CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) 
  values (SEQ_QUESTIONNAIRE_REF_ID.nextval,
  (select MAX(QUESTIONNAIRE_REF_ID) from QUESTIONNAIRE where NAME='PHS Assignment Request Form V1.0'),
  (select MAX(QUESTION_REF_ID) from QUESTION where QUESTION_ID=100027),
  3,2,'Y','4','Y',sysdate,'admin',3,1,SYS_GUID(),null);

-- 1b. Do Not Assign to Awarding Component?
Insert into QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) 
   values (SEQ_QUESTIONNAIRE_REF_ID.nextval,100028,1,'A','Are there Awarding Components that you do NOT want assigned?',
   'A',2,1,null,null,null,1,1,sysdate,'admin',1,sys_guid(),null);
   
Insert into QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,
     CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) 
  values (SEQ_QUESTIONNAIRE_REF_ID.nextval,
  (select MAX(QUESTIONNAIRE_REF_ID) from QUESTIONNAIRE where NAME='PHS Assignment Request Form V1.0'),
  (select MAX(QUESTION_REF_ID) from QUESTION where QUESTION_ID=100028),
  4,1,'Y','4','Y',sysdate,'admin',4,1,SYS_GUID(),null);

-- 1bi. Assign to Awarding Component Fields?
Insert into QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) 
   values (SEQ_QUESTIONNAIRE_REF_ID.nextval,100029,1,'A','Do NOT assign to Awarding Component.',
   'A',4,5,null,null,null,3,7,sysdate,'admin',1,sys_guid(),null);
   
Insert into QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,
     CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) 
  values (SEQ_QUESTIONNAIRE_REF_ID.nextval,
  (select MAX(QUESTIONNAIRE_REF_ID) from QUESTIONNAIRE where NAME='PHS Assignment Request Form V1.0'),
  (select MAX(QUESTION_REF_ID) from QUESTION where QUESTION_ID=100029),
  5,4,'Y','4','Y',sysdate,'admin',5,1,SYS_GUID(),null);

-- QUESTION 2 STUDY SECTION
-- 2. Study Section Assignment?

Insert into QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) 
   values (SEQ_QUESTIONNAIRE_REF_ID.nextval,100030,1,'A','If you have a preference for a study section assignment, please use the link https://grants.nih.gov/grants/phs_assignment_information.htm#StudySection to identify the most appropriate study section then enter the short abbreviation for that study section in Assign to/Do not Assign to Study Section sections below. Do you have a preference for a Study Section Assignment?',
   'A',2,1,null,null,null,1,1,sysdate,'admin',1,sys_guid(),null);
   
Insert into QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,
     CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) 
  values (SEQ_QUESTIONNAIRE_REF_ID.nextval,
  (select MAX(QUESTIONNAIRE_REF_ID) from QUESTIONNAIRE where NAME='PHS Assignment Request Form V1.0'),
  (select MAX(QUESTION_REF_ID) from QUESTION where QUESTION_ID=100030),
  6,0,'N',null,null,sysdate,'admin',6,1,SYS_GUID(),null);

-- 2a. Assign to Study Section?
Insert into QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) 
   values (SEQ_QUESTIONNAIRE_REF_ID.nextval,100031,1,'A','Do you need to assign to Study Section?',
   'A',2,1,null,null,null,1,1,sysdate,'admin',1,sys_guid(),null);
   
Insert into QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,
     CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) 
  values (SEQ_QUESTIONNAIRE_REF_ID.nextval,
  (select MAX(QUESTIONNAIRE_REF_ID) from QUESTIONNAIRE where NAME='PHS Assignment Request Form V1.0'),
  (select MAX(QUESTION_REF_ID) from QUESTION where QUESTION_ID=100031),
  7,6,'Y','4','Y',sysdate,'admin',7,1,SYS_GUID(),null);

-- 2ai. Assign to Study Section Fields?
Insert into QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) 
   values (SEQ_QUESTIONNAIRE_REF_ID.nextval,100032,1,'A','Assign to Study Section.',
   'A',4,5,null,null,null,3,20,sysdate,'admin',1,sys_guid(),null);
   
Insert into QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,
     CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) 
  values (SEQ_QUESTIONNAIRE_REF_ID.nextval,
  (select MAX(QUESTIONNAIRE_REF_ID) from QUESTIONNAIRE where NAME='PHS Assignment Request Form V1.0'),
  (select MAX(QUESTION_REF_ID) from QUESTION where QUESTION_ID=100032),
  8,7,'Y','4','Y',sysdate,'admin',8,1,SYS_GUID(),null);


-- 2b. Do Not Assign to Study Section?
Insert into QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) 
   values (SEQ_QUESTIONNAIRE_REF_ID.nextval,100033,1,'A','Are there Study Sections that you do NOT want assigned?',
   'A',2,1,null,null,null,1,1,sysdate,'admin',1,sys_guid(),null);
   
Insert into QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,
     CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) 
  values (SEQ_QUESTIONNAIRE_REF_ID.nextval,
  (select MAX(QUESTIONNAIRE_REF_ID) from QUESTIONNAIRE where NAME='PHS Assignment Request Form V1.0'),
  (select MAX(QUESTION_REF_ID) from QUESTION where QUESTION_ID=100033),
  9,6,'Y','4','Y',sysdate,'admin',9,1,SYS_GUID(),null);

-- 2bi. Assign to Awarding Component Fields?
Insert into QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) 
   values (SEQ_QUESTIONNAIRE_REF_ID.nextval,100034,1,'A','Do NOT assign to Study Section.',
   'A',4,5,null,null,null,3,20,sysdate,'admin',1,sys_guid(),null);
   
Insert into QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,
     CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) 
  values (SEQ_QUESTIONNAIRE_REF_ID.nextval,
  (select MAX(QUESTIONNAIRE_REF_ID) from QUESTIONNAIRE where NAME='PHS Assignment Request Form V1.0'),
  (select MAX(QUESTION_REF_ID) from QUESTION where QUESTION_ID=100034),
  10,9,'Y','4','Y',sysdate,'admin',10,1,SYS_GUID(),null);

-- QUESTION 3 INDIVIDUALS WHOM SHOULD NOT REVIEW
-- 3. Are there individuals whom should not review your application?
Insert into QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) 
   values (SEQ_QUESTIONNAIRE_REF_ID.nextval,100035,1,'A','Are there individuals whom should NOT review your application?',
   'A',2,1,null,null,null,1,1,sysdate,'admin',1,sys_guid(),null);
   
Insert into QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,
     CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) 
  values (SEQ_QUESTIONNAIRE_REF_ID.nextval,
  (select MAX(QUESTIONNAIRE_REF_ID) from QUESTIONNAIRE where NAME='PHS Assignment Request Form V1.0'),
  (select MAX(QUESTION_REF_ID) from QUESTION where QUESTION_ID=100035),
  11,0,'N',null,null,sysdate,'admin',11,1,SYS_GUID(),null);

-- 3b. Assign to Awarding Component Fields?
Insert into QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) 
   values (SEQ_QUESTIONNAIRE_REF_ID.nextval,100036,1,'A','List Individuals who should NOT review your application and why.',
   'A',4,5,null,null,null,1,1000,sysdate,'admin',1,sys_guid(),null);
   
Insert into QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,
     CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) 
  values (SEQ_QUESTIONNAIRE_REF_ID.nextval,
  (select MAX(QUESTIONNAIRE_REF_ID) from QUESTIONNAIRE where NAME='PHS Assignment Request Form V1.0'),
  (select MAX(QUESTION_REF_ID) from QUESTION where QUESTION_ID=100036),
  12,11,'Y','4','Y',sysdate,'admin',12,1,SYS_GUID(),null);

-- QUESTION 4 IDENTIFY SCIENTIFIC AREAS OF EXPERTISE 
-- 4. Are there scientific areas of expertise needed to review your application?
Insert into QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) 
   values (SEQ_QUESTIONNAIRE_REF_ID.nextval,100037,1,'A','Are there scientific areas of expertise needed to review your application?',
   'A',2,1,null,null,null,1,1,sysdate,'admin',1,sys_guid(),null);
   
Insert into QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,
     CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) 
  values (SEQ_QUESTIONNAIRE_REF_ID.nextval,
  (select MAX(QUESTIONNAIRE_REF_ID) from QUESTIONNAIRE where NAME='PHS Assignment Request Form V1.0'),
  (select MAX(QUESTION_REF_ID) from QUESTION where QUESTION_ID=100037),
  13,0,'N',null,null,sysdate,'admin',13,1,SYS_GUID(),null);

-- 4b. Identify Scientific areas of expertise needed to review your application
Insert into QUESTION (QUESTION_REF_ID,QUESTION_ID,SEQUENCE_NUMBER,SEQUENCE_STATUS,QUESTION,STATUS,GROUP_TYPE_CODE,QUESTION_TYPE_ID,LOOKUP_CLASS,LOOKUP_RETURN,DISPLAYED_ANSWERS,MAX_ANSWERS,ANSWER_MAX_LENGTH,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,DOCUMENT_NUMBER) 
   values (SEQ_QUESTIONNAIRE_REF_ID.nextval,100038,1,'A','Identify Scientific areas of expertise needed to review your application. Please do NOT provide names of individuals.',
   'A',4,5,null,null,null,5,40,sysdate,'admin',1,sys_guid(),null);
   
Insert into QUESTIONNAIRE_QUESTIONS (QUESTIONNAIRE_QUESTIONS_ID,QUESTIONNAIRE_REF_ID_FK,QUESTION_REF_ID_FK,QUESTION_NUMBER,PARENT_QUESTION_NUMBER,CONDITION_FLAG,CONDITION_TYPE,
     CONDITION_VALUE,UPDATE_TIMESTAMP,UPDATE_USER,QUESTION_SEQ_NUMBER,VER_NBR,OBJ_ID,RULE_ID) 
  values (SEQ_QUESTIONNAIRE_REF_ID.nextval,
  (select MAX(QUESTIONNAIRE_REF_ID) from QUESTIONNAIRE where NAME='PHS Assignment Request Form V1.0'),
  (select MAX(QUESTION_REF_ID) from QUESTION where QUESTION_ID=100038),
  14,13,'Y','4','Y',sysdate,'admin',14,1,SYS_GUID(),null);



 -- RES-711
alter table EPS_PROPOSAL ADD AGENCY_PROGRAM_NAME VARCHAR2(200);
alter table EPS_PROPOSAL ADD AGENCY_DIVISION_NAME VARCHAR2(200);


 -- RES-710
CREATE SEQUENCE SEQ_S2S_ERROR_MESSAGES INCREMENT BY 1 START WITH 1 NOCACHE;

  CREATE TABLE "S2S_ERROR_MESSAGES" 
   (	"ERROR_MESSAGE_ID" NUMBER NOT NULL ENABLE, 
	"FORM_DESC" VARCHAR2(200 BYTE), 
	"MESSAGE_KEY" VARCHAR2(300 BYTE) NOT NULL ENABLE, 
	"MESSAGE_DESC" VARCHAR2(400 BYTE) NOT NULL ENABLE, 
        "ACTIVE" VARCHAR2(1 BYTE) NOT NULL ENABLE,
	"FIXLINK" VARCHAR2(100 BYTE), 
	"UPDATED_DATE" TIMESTAMP (6), 
	"UPDATED_USER" VARCHAR2(60 BYTE), 
	"OBJ_ID" VARCHAR2(36 BYTE) NOT NULL ENABLE, 
	"VER_NBR" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "S2S_ERROR_MESSAGES_PK" PRIMARY KEY ("ERROR_MESSAGE_ID") ENABLE
   );

  CREATE INDEX "IDX_S2SERROR_KEY" ON "S2S_ERROR_MESSAGES" ("MESSAGE_KEY");


-- RES-685
alter table BUDGET_DETAILS rename column IS_FORMULATED_COST_ELELMENT TO IS_FORMULATED_COST_ELEMENT;


 --RES-657
Declare
  nextnum NUMBER;
 BEGIN
  select (NVL(MAX(AWARD_PERSON_ID),0)+1) into nextnum from AWARD_PERSONS;
  execute immediate 'CREATE SEQUENCE "SEQ_AWARD_PERSONS_ID" MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH ' || nextnum || ' NOCACHE  ORDER  NOCYCLE';
END;

/
--RES-658
Declare
  nextnum NUMBER;
 BEGIN
  select (NVL(MAX(AWARD_PERSON_UNIT_ID),0)+1) into nextnum from AWARD_PERSON_UNITS;
  execute immediate 'CREATE SEQUENCE "SEQ_AWARD_PERSON_UNITS_ID" MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH ' || nextnum || ' NOCACHE  ORDER  NOCYCLE';
END;

/
--RES-659
Declare
  nextnum NUMBER;
 BEGIN
  select (NVL(MAX(AWARD_PERSON_CREDIT_SPLIT_ID),0)+1) into nextnum from AWARD_PERSON_CREDIT_SPLITS;
  execute immediate 'CREATE SEQUENCE "SEQ_AWARD_PERSON_CREDSPLITS_ID" MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH ' || nextnum || ' NOCACHE  ORDER  NOCYCLE';
END;

/
--RES-660
Declare
  nextnum NUMBER;
 BEGIN
  select (NVL(MAX(APU_CREDIT_SPLIT_ID),0)+1) into nextnum from AWARD_PERS_UNIT_CRED_SPLITS;
  execute immediate 'CREATE SEQUENCE "SEQ_AWARD_PERS_UNITCREDSPLS_ID" MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH ' || nextnum || ' NOCACHE  ORDER  NOCYCLE';
END;

/

--RES-667
Declare
  nextnum NUMBER;
 BEGIN
  select (NVL(MAX(AWARD_APPROVED_EQUIPMENT_ID),0)+1) into nextnum from AWARD_APPROVED_EQUIPMENT;
  execute immediate 'CREATE SEQUENCE "SEQ_AWARD_APPRV_EQUIPMENT_ID" MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH ' || nextnum || ' NOCACHE  ORDER  NOCYCLE';
END;

/
--RES-668
Declare
  nextnum NUMBER;
 BEGIN
  select (NVL(MAX(AWARD_APPR_FORN_TRAVEL_ID),0)+1) into nextnum from AWARD_APPROVED_FOREIGN_TRAVEL;
  execute immediate 'CREATE SEQUENCE "SEQ_AWARD_APPRV_FORNEQUIP_ID" MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH ' || nextnum || ' NOCACHE  ORDER  NOCYCLE';
END;

/







 -- RES-546
Declare
  nextnum NUMBER;
 BEGIN
  select (NVL(MAX(TO_NUMBER(SPECIAL_REVIEW_CODE)),0)+1) into nextnum from SPECIAL_REVIEW;
  execute immediate 'CREATE SEQUENCE "SEQ_SPECIAL_REVIEW_ID" MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH ' || nextnum || ' NOCACHE  ORDER  NOCYCLE';
END;

/

Declare
  nextnum NUMBER;
 BEGIN
  select (NVL(MAX(TO_NUMBER(TBN_ID)),0)+1) into nextnum from TBN;
  execute immediate 'CREATE SEQUENCE "SEQ_TBN_ID" MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH ' || nextnum || ' NOCACHE  ORDER  NOCYCLE';
END;

commit;
exit
